name: change_copy  # 项目标识名，可以保持不变或改为 change
description: "A copy of the original app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  uuid: ^3.0.4  # 调整为 3.0.4（之前的代码使用此版本）
  shared_preferences: ^2.3.2
  path_provider: ^2.0.0  # 调整为 2.0.0
  permission_handler: ^11.3.0  # 添加权限处理包
  device_info_plus: ^11.3.0
  sqflite: ^2.0.0+4  # 调整为 2.0.0+4
  path: ^1.8.0  # 调整为 1.8.0
  image_picker: ^0.8.0+4  # 调整为 0.8.0+4
  photo_manager: ^3.5.1
  video_player: ^2.9.2
  chewie: ^1.7.1  # 添加chewie视频播放UI组件
  flutter_colorpicker: ^1.0.3  # 调整为 1.0.3
  archive: ^4.0.4
  file_picker: ^9.0.2
  share_plus: ^10.1.1
  win32: ^5.8.0
  audioplayers: ^6.4.0
  record: ^5.2.1
  ffmpeg_kit_flutter_full: ^6.0.3  # 添加FFmpeg包
  crypto: ^3.0.3  # 添加crypto包用于生成哈希值

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/media/

  # 添加字体配置（根据需要解注释）
  # fonts:
  #   - family: Arial
  #     fonts:
  #       - asset: assets/fonts/Arial.ttf
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true  # 添加此行以移除 iOS 图标的 alpha 通道
